# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      keycloak:
        description: "Keycloak version"
        required: true
        default: "latest"
      justauth:
        description: "Justauth version"
        required: true
        default: "latest"
      prerelease:
        description: "Prerelease"
        required: true
        default: true
        type: choice
        options:
        - true
        - false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Python Dependencies
      run: pip3 install requests
    - name: Gen Pom.xml
      shell: python
      run: |
          import requests
          import re
          import os

          def check_maven_latest(group, artifact):
            res = requests.get(f"https://repo1.maven.org/maven2/{group.replace('.', '/')}/{artifact}/maven-metadata.xml")
            return re.findall(r'<latest>(.*?)</latest>', res.text)[0]

          def gen_pom(keycloak_version, justauth_version, hutool_version):
            raw = f"""<?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
          
            <parent>
              <groupId>org.keycloak</groupId>
              <artifactId>keycloak-parent</artifactId>
              <version>{keycloak_version}</version>
            </parent>
          
            <groupId>com.yfwj</groupId>
            <artifactId>keycloak-justauth</artifactId>
            <packaging>jar</packaging>
            <properties>
              <maven.compiler.source>1.8</maven.compiler.source>
              <maven.compiler.target>1.8</maven.compiler.target>
              <justauth.version>{justauth_version}</justauth.version>
            </properties>
          
            <dependencies>
              <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-core</artifactId>
                <scope>provided</scope>
              </dependency>
              <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-server-spi</artifactId>
                <scope>provided</scope>
              </dependency>
              <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-server-spi-private</artifactId>
                <scope>provided</scope>
              </dependency>
              <dependency>
                <groupId>org.jboss.logging</groupId>
                <artifactId>jboss-logging</artifactId>
                <scope>provided</scope>
              </dependency>
              <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-services</artifactId>
                <scope>provided</scope>
              </dependency>
          
              <dependency>
                <groupId>me.zhyd.oauth</groupId>
                <artifactId>JustAuth</artifactId>
                <version>{justauth_version}</version>
              </dependency>
              <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-http</artifactId>
                <version>{hutool_version}</version>
              </dependency>
            </dependencies>
          
            <build>
              <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                      <source>1.8</source>
                      <target>1.8</target>
                    </configuration>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.3.0</version>
                    <configuration>
                      <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                      </descriptorRefs>
                      <archive>
                        <manifestEntries>
                          <Dependencies>org.keycloak.keycloak-services</Dependencies>
                        </manifestEntries>
                      </archive>
                    </configuration>
          
                    <executions>
                      <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                          <goal>single</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
              </plugins>
            </build>
          </project>"""
            return raw

          if __name__ == '__main__':
            keycloak_version = "${{ github.event.inputs.keycloak }}" or 'latest'
            justauth_version = "${{ github.event.inputs.justauth }}" or 'latest'
            if keycloak_version == 'latest':
              keycloak_version = check_maven_latest("org.keycloak", "keycloak-parent")
            if justauth_version == 'latest':
              justauth_version = check_maven_latest("me.zhyd.oauth", "JustAuth")
            hutool_version = check_maven_latest("cn.hutool", "hutool-http")
            if keycloak_version and keycloak_version != 'latest' and justauth_version and justauth_version != 'latest' and hutool_version and hutool_version != 'latest':
              print(f"Keycloak: {keycloak_version}\nJustauth: {justauth_version}\nHutool: {hutool_version}")
              pom = gen_pom(keycloak_version, justauth_version, hutool_version)
              open('pom.xml', 'w').write(pom)
              with open(os.environ['GITHUB_ENV'], 'a') as g:
                g.write(f'KEYCLOAK_VERSION={keycloak_version}\n')
                g.write(f'JUSTAUTH_VERSION={justauth_version}\n')
                g.write(f'HUTOOL_VERSION={hutool_version}\n')
                g.write(f'artifact_name=Keycloak-Justauth_{keycloak_version}_{justauth_version}\n')
              print('Gen version success')
            else:
              print('Get latest version error')
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ env.artifact_name }}
        path: target/*.jar
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        body: "```\nKeycloak Version: ${{ env.KEYCLOAK_VERSION }}\nJustauth Version: ${{ env.JUSTAUTH_VERSION }}\nHutool Version: ${{ env.HUTOOL_VERSION }}\n```"
        tag_name: ${{ env.KEYCLOAK_VERSION }}
        files: target/*.jar
        prerelease: ${{ github.event.inputs.prerelease }}
        fail_on_unmatched_files: true
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log in to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          keycloak_version=${{ env.KEYCLOAK_VERSION }}
        tags: |
          ztelliot/keycloak-justauth:${{ env.KEYCLOAK_VERSION }}
          ghcr.io/ztelliot/keycloak-justauth:${{ env.KEYCLOAK_VERSION }}
    - name: Build and Push Docker images as Latest
      uses: docker/build-push-action@v2
      if: ${{ github.event.inputs.prerelease != 'true' }}
      with:
        context: .
        push: true
        build-args: |
          keycloak_version=${{ env.KEYCLOAK_VERSION }}
        tags: |
          ztelliot/keycloak-justauth:latest
          ghcr.io/ztelliot/keycloak-justauth:latest
